eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9086
spring:
  application:
    name: gipher-recommender-service
  data:
    mongodb:
      database: gipherdb
      uri: mongodb://localhost:27017/gipherdb
