spring:
 data:
  mongodb:
   database: SBA
   port: 27017
   host: localhost   
 application:
    name: gipher-recommender-service
server:
  port: 8090
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka