image: "java:8-jdk"
stages:
    - test
    - build
services:
    - 'mysql:5.6'
    - 'mongo:latest'
variables:
    MYSQL_DATABASE: gipherUserDb
    MYSQL_URL: jdbc:mysql://mysql/gipherUserDb
    MYSQL_USER: app-root
    MYSQL_PASSWORD: root123
    MYSQL_ROOT_PASSWORD: root
    MONGO_DATABASENAME: gipherdb
    MONGO_URL: mongodb://mongo/gipherdb
cache:
    paths:
    - .m2/repository
maven-test:
    image: maven:3.5.2-jdk-8
    stage: test
    script: "mvn test"
maven-build:
    image: maven:3.5.2-jdk-8
    stage: build
    script: "mvn clean install -Dmaven.test.skip=true"
