spring:
  application:
    name: account-manager-service
  datasource:
    url: jdbc:mysql://localhost:3306/gipheruserdb
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9084
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka